user_homepage:
    path:     /hello/{name}
    defaults: { _controller: UserBundle:Default:index }
edit_profil:
    path:     /user/edit/{id}
    defaults: { _controller: UserBundle:Registration:editer }
lister_user:
    path:     /user/lister
    defaults: { _controller: UserBundle:Registration:lister }
lister_user_xml:
    path:     /user/liste/{rech}
    defaults: { _controller: UserBundle:Registration:liste, rech:0}
recherche_user:
    path:     /user/recherche
    defaults: { _controller: UserBundle:Registration:recherche}