user_homepage:
    path:     /hello/{name}
    defaults: { _controller: UserBundle:Default:index }
edit_profil:
    path:     /user/edit/{id}
    defaults: { _controller: UserBundle:Registration:editer }
