projet_homepage:
    path:     /
    defaults: { _controller: ProjetBundle:Default:index }
ajouter_publication:
    path:     /publication/ajouter
    defaults: { _controller: ProjetBundle:Publication:ajouter }
voir_publication:
    path:     /publication/{id}
    defaults: { _controller: ProjetBundle:Publication:voir }
